#:kivy 2.2.1

<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        Label:
            id: welcomeLabel
            text: "hello riley"
            font_size: 32

        GridLayout:
            cols: 2

            Label:
                id: checkboxLabel1
                text: "test checkbox"
                font_size: 20
            CheckBox:
                on_active: root.checkbox_click(self, self.active)

                



    

